# Generated by Django 4.1 on 2024-01-13 00:24

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=50, null=True)),
                ("topic", models.CharField(blank=True, max_length=200, null=True)),
                ("tags", models.CharField(blank=True, max_length=300, null=True)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("DELETED", "Deleted"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
